# Definir la sección de eventos
events {
    worker_connections 1024;  # Número máximo de conexiones que un worker puede manejar
}

# Definir el contexto HTTP
http {
  # Configuración del servidor
  server {
    listen 80;  # El puerto en el que escucha Nginx
    server_name sistema-reservas-canchas-backend.onrender.com;

    # Root de los archivos de Angular
    root /usr/share/nginx/html;
    index index.html;

    # Redirigir todas las rutas al index.html para que Angular maneje las rutas
    location / {
      try_files $uri $uri/ /index.html;
    }

    # Configuración para errores 404
    error_page 404 /index.html;
  }
}
